# Generated by Django 3.1.1 on 2020-12-01 02:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentID', models.IntegerField()),
                ('comment', models.TextField()),
            ],
            options={
                'db_table': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailID', models.IntegerField()),
                ('mode', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Details',
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratingID', models.IntegerField()),
                ('rate', models.IntegerField()),
            ],
            options={
                'db_table': 'Ratings',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiptID', models.IntegerField()),
                ('userID', models.IntegerField()),
            ],
            options={
                'db_table': 'Receipt',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduleId', models.IntegerField()),
                ('session_date', models.DateField()),
                ('session_time', models.TimeField()),
                ('curr_date', models.DateField(default=django.utils.timezone.localdate)),
                ('curr_time', models.DateField(default=django.utils.timezone.localtime)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Schedule',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectID', models.IntegerField(null=True)),
                ('subjectName', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Subject',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('firstName', models.CharField(blank=True, max_length=100, null=True)),
                ('middleName', models.CharField(blank=True, max_length=100, null=True)),
                ('lastName', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contactNo', models.IntegerField(null=True)),
                ('userID', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.user')),
                ('adminID', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'Admin',
            },
            bases=('pages.user',),
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.user')),
                ('menteeID', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'Mentee',
            },
            bases=('pages.user',),
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.user')),
                ('mentorID', models.IntegerField(null=True)),
                ('achvemnts', models.BooleanField()),
                ('proofs', models.BooleanField()),
            ],
            options={
                'db_table': 'Mentor',
            },
            bases=('pages.user',),
        ),
        migrations.CreateModel(
            name='TutorialPayment',
            fields=[
                ('TPaymentID', models.IntegerField(primary_key=True, serialize=False)),
                ('total', models.FloatField()),
                ('scheduleID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.schedule')),
            ],
            options={
                'db_table': 'TutorialPayment',
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.subject'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountID', models.IntegerField()),
                ('detailID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.details')),
                ('receiptID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.receipt')),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.user')),
            ],
            options={
                'db_table': 'Account',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='mentorID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.mentor'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='menteeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.mentee'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewID', models.IntegerField()),
                ('comments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.comments')),
                ('ratings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.ratings')),
                ('menteeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.mentee')),
                ('mentorID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.mentor')),
            ],
            options={
                'db_table': 'Review',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageID', models.IntegerField()),
                ('message', models.TextField()),
                ('menteeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.mentee')),
            ],
            options={
                'db_table': 'Messages',
            },
        ),
    ]
