# Generated by Django 3.1.1 on 2020-12-07 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_subject_session_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='session_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subject',
            name='session_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
