# Generated by Django 3.1.1 on 2020-12-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20201207_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='session_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='subject',
            name='session_time',
            field=models.TimeField(default=None),
        ),
    ]
