# Generated by Django 3.1.1 on 2020-12-07 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_input'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Input',
        ),
    ]
