# Generated by Django 3.1.1 on 2020-12-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_delete_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='mode',
        ),
        migrations.AddField(
            model_name='details',
            name='cardNumber',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='details',
            name='cardOwnerName',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='details',
            name='cvc',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='details',
            name='expire_month',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='details',
            name='expire_year',
            field=models.IntegerField(default=None),
        ),
    ]
