# Generated by Django 3.1.1 on 2020-12-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20201207_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='cardNumber',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='cvc',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='expire_month',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='expire_year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
