# Generated by Django 3.1.1 on 2020-12-09 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20201208_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(default=' ', max_length=500, null=True)),
                ('menteeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.mentee')),
                ('mentorID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.mentor')),
                ('subjectID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.subject')),
            ],
        ),
    ]
