# Generated by Django 3.1.1 on 2020-12-09 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_notes'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notes',
            table='Notes',
        ),
    ]
