# Generated by Django 3.1.1 on 2020-12-09 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20201209_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='notesTitle',
            field=models.CharField(default=' ', max_length=500, null=True),
        ),
    ]
