# Generated by Django 3.1.1 on 2020-12-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_notes_notestitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='session_time',
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='subject',
            name='session_time_start',
            field=models.CharField(default='00:00', max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subjectName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
