# Generated by Django 3.1.1 on 2020-12-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20201214_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='session_time_end',
            field=models.CharField(default='00:00', max_length=10),
        ),
    ]
