# Generated by Django 3.1.1 on 2020-12-14 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_subject_session_time_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='curr_date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='curr_time',
        ),
    ]
