# Generated by Django 3.1.1 on 2020-12-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20201215_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='custom_time_end',
            field=models.CharField(default='00:00', max_length=10),
        ),
        migrations.AddField(
            model_name='schedule',
            name='custom_time_start',
            field=models.CharField(default='00:00', max_length=10),
        ),
        migrations.AddField(
            model_name='schedule',
            name='payment_method',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time',
            field=models.CharField(default='00:00-00:00', max_length=10),
        ),
    ]
