# Generated by Django 3.1.1 on 2020-12-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20201215_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='schedule',
            name='ratePrHour',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5),
        ),
    ]
