# Generated by Django 3.1.1 on 2020-12-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20201215_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
